version: '2'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql-library
    volumes:
      - ./data/mariadb-library:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testes
      - MYSQL_DATABASE=library_admin
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox
      
  redis:
    image: redis:alpine
    container_name: redis-library
    volumes:
      - redis-data:/data
  php:
    build:
      context: .
      dockerfile: ./docker/php7-fpm/Dockerfile
    image: repo-registry-local.ftd.com.br:5000/libraryapitest-app:v4.0
    container_name: php-library
    depends_on:
      - redis
      - mysql
    command: bash -c "php artisan migrate && php-fpm"
    environment:
      APP_KEY: base64:a89Bj62VIrzfDCsb3m8BNU+JedVKtEZEmqif25fR2g0=
      APP_ENV: local
      DB_PORT: 3306
      DB_USERNAME: sandbox
      DB_DATABASE: library_admin
      DB_PASSWORD: sandbox
      DB_HOST: mysql
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      DEBUG: 1
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: Monolog\Formatter\JsonFormatter    
    links:
      - mysql
      - redis
    volumes:
     - ./application/:/app:rw
  worker-php:
    build:
      context: .
      dockerfile: ./docker/php7-fpm/Dockerfile
    image: libraryapiotra:php-worker
    container_name: php-library-worker
    depends_on:
      - redis
      - mysql
    command: sh -c "crontab scheduler.txt; cron -f; php-fpm  ; php-fpm -v"
    environment:
      APP_KEY: base64:a89Bj62VIrzfDCsb3m8BNU+JedVKtEZEmqif25fR2g0=
      APP_ENV: local
      DB_PORT: 3306
      DB_USERNAME: sandbox
      DB_DATABASE: library_admin
      DB_PASSWORD: sandbox
      DB_HOST: mysql
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      DEBUG: 1
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: Monolog\Formatter\JsonFormatter  
    links:
      - mysql
      - redis
    volumes:
      - ./application/:/app:rw

  web:
    image: nginx:1.19-alpine
    container_name: nginx-library
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
      - ./application/:/app:rw
    ports:
      - 80:80

volumes:
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"