version: '2'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql-library
    volumes:
      - ./data/mariadb-library:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testes
      - MYSQL_DATABASE=library_admin
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox
      
  redis:
    image: redis:alpine
    container_name: redis-library
    volumes:
      - redis-data:/data
  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php-library
    depends_on:
      - redis
      - mysql
    command: bash -c "sh crontab-install.sh && php-fpm  && php-fpm -v"
    environment:
      APP_ENV: local
      DB_PORT: 3306
      DB_USERNAME: sandbox
      DB_DATABASE: library_admin
      DB_PASSWORD: sandbox
      DB_HOST: mysql
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      DEBUG: 1
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis      
    links:
      - mysql
      - redis
    volumes:
      - ./application/:/var/www/html:rw

  web:
    image: nginx:alpine
    container_name: nginx-library
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"