# Isso aqui é um serviço para me conectar ao meu mysql no servidor da google cloud

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  ports:
    - port: 3306    
  selector:
    app:  app-mysql
    tier: mysql
  clusterIP: None