apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-inutil
spec:
  schedule: "*/45 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: brunocaramelo/libraryapitest-app:v4.0
            name: job-inutil
            command: ["php", "artisan", "schedulerInutil:run"]
            envFrom:
            - configMapRef:
                name: app-conf
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-cuspidor-log
spec:
  schedule: "*/55 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: brunocaramelo/libraryapitest-app:v4.0
            name: job-cuspidor-log
            command: ["php", "artisan", "cuspirlog:run","--parametrozao=valorAqui"]
            envFrom:
            - configMapRef:
                name: app-conf
          restartPolicy: Never
