apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.name}-v${version.major}
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.name}-v${version.major}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: extensions/v2beta2
          kind: Ingress
          name: ${project.name}
        target:
          type: Value
          value: 1k
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.name}-v${version.major}-web
spec:
  minReplicas: 1
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.name}-v${version.major}-web
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50 
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: extensions/v2beta2
          kind: Ingress
          name: ${project.name}
        target:
          type: Value
          value: 1k
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.name}-v${version.major}-queue
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.name}-v${version.major}-queue
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 
   